return {
  -- "neovim/nvim-lspconfig",
  -- dependencies = { "saghen/blink.cmp" },
  --
  -- config = function()
  --   local capabilities = require("blink.cmp").get_lsp_capabilities()
  --   local lspconfig = require("lspconfig")
  --
  --   lspconfig["lua_ls"].setup({ capabilities = capabilities })
  --
  --   lspconfig["rust_analyzer"].setup({ capabilities = capabilities })
  --
  --   lspconfig["pyright"].setup({ capabilities = capabilities })
  --   -- lspconfig["basedpyright"].setup({ capabilities = capabilities })
  --   -- lspconfig["debugpy"].setup({ capabilities = capabilities })
  --
  --   lspconfig["clangd"].setup({ capabilities = capabilities })
  --   -- lspconfig["codelldb"].setup({ capabilities = capabilities })
  --
  --   lspconfig["bashls"].setup({ capabilities = capabilities })
  --
  --   lspconfig["jsonls"].setup({ capabilities = capabilities })
  -- end,
}
